### ISSUE TITLE
Logging for ioredis

### ISSUE THREAD

**Issue by vazaio** [launchdarkly/node-server-sdk-redis#11]
Hello LD team and @eli-darkly :rocket:

**Is your feature request related to a problem? Please describe.**
As it's highlighted in docs **node-server-sdk-redis** should work fine with **Node-Redis** lib. But I use it with **ioredis** and it's alive except 1 thing - logging from ```redis_base.js``` for *"reconnecting"* event.

Let's take a look at **ioredis** clients:
1) Base client - it emits *"reconnecting"* with 1 argument ```retryDelay``` 
```js
// https://github.com/luin/ioredis/blob/master/lib/redis/event_handler.ts#L196
self.setStatus("reconnecting", retryDelay);
```
So the logger logs ```info.attempt``` and ```info.delay``` but info is ```retryDelay``` number and we see *undefined* at logs. it's not good, but not critical

2) Cluster client - it emits *"reconnecting"* without any arguments
```js
// https://github.com/luin/ioredis/blob/master/lib/cluster/index.ts#L325
this.setStatus("reconnecting");
```
The logger tries to log ```attempt``` and ```delay``` same as above and ```info``` equals ```undefined```. As a result **uncaughtException** *Cannot read property 'attempt' of undefined* pops up :cry:

**Describe the solution you'd like**
As for me the simplest solution is:
```js
state.client.on('reconnecting', (info = {}) => {
  logger.info('Attempting to reconnect to Redis (attempt #' + info.attempt + ', delay: ' + info.delay + 'ms)');
});
```

**Describe alternatives you've considered**
Probably you can detect a type of ```info``` to determine (approximately) what lib is used
```js
state.client.on('reconnecting', (info) => {
  if (isObject(info)) {
    logger.info('Attempting to reconnect to Redis (attempt #' + info.attempt + ', delay: ' + info.delay + 'ms)');
  } else if (isNumber(info)) {
    logger.info('Attempting to reconnect to Redis (retry delay: ' + info + 'ms)');
  } else {
    logger.info('Attempting to reconnect to Redis');
  }
});
```

**Additional context**
Versions:
node 14.18.0
launchdarkly-node-server-sdk-redis 2.0.0
launchdarkly-node-server-sdk 6.2.1
ioredis 4.14.1

**Comment by kinyoklion** [comment]
Hello @vazaio,

The Redis integration only supports Node-Redis. Which introduces some issues with maintenance and complexity for making specific fixes for unsupported Redis implementations. The fix may not make sense in the context of Node-Redis only, so could be optimized away and not caught by testing. Additionally, the APIs between Node-Redis and ioredis may be largely similar, but there are some differences, and also no guarantee of continued compatibility. In general, implementing this change would not result in official support for ioredis, and we couldn't recommend or support that configuration.

I've put a request for ioredis support for node-server-sdk-redis into our backlog.

Thank you,
Ryan

**Comment by rektide** [comment]
Crude measure, but ioredis has just as many downloads as redis. It's significantly faster & has been ahead of the curve with things like promises. It's super popular.

We have a number of apps which have had to double back & create an old-fashioned `redis` instance to support launchdarkly. It's a bit of an eyesore & ugly. Would very much love ioredis support. I realize it's work for the team to validate that things work as expected, but given the very very positive ease with which @vazaio found getting things working, I'd re-encourage the LD node sdk team to please kindly make using LD a little more node.js-normal if they can.
