### ISSUE TITLE
Support v4 Redis

### ISSUE THREAD

**Issue by rektide** [launchdarkly/node-server-sdk-redis#12]
It'd be nice to [migrate from v3 -> v4](https://github.com/redis/node-redis/blob/master/docs/v3-to-v4.md). This is now >1 year old & has seen a lot of work on various pieces (such as reconnect strategies), and has typescript built in. [Release notes](https://github.com/redis/node-redis/releases/tag/redis%404.0.0).

In general it'd probably be a good time to switch to promises, although that's optional. There are no longer any Node.js releases without promises.

**Comment by kinyoklion** [comment]
Hello @rektide,

Thank you for the issue. In regards to promises there are some changes in progress, but I cannot provide an ETA.

_Filed internally 169130._

Thank you,
Ryan

**Comment by kinyoklion** [comment]
Hello @rektide,

The new version of the SDK, v8,uses ioredis and should support v4.

The new version has a new location and package.

The new version is located here: https://github.com/launchdarkly/js-core/tree/main/packages/sdk/server-node
It also has a new package name, `@launchdarkly/node-server-sdk`.

The redis package is also moved and renamed.

Github: https://github.com/launchdarkly/js-core/tree/main/packages/store/node-server-sdk-redis
Npm: https://www.npmjs.com/package/@launchdarkly/node-server-sdk-redis

Thank you,
Ryan

**Comment by kinyoklion** [comment]
Closing this issue as it is addressed in the latest version. If there are problems, then an issue can be opened in the new location.
